### ISSUE TITLE
Publish JavaDoc to Github Pages

### ISSUE THREAD

**Issue by prateek** [uber-java/tally#6]
Will be useful for end-users to have a place to go for documentation. Example blog setting this up with Travis+Maven+Github Pages:  [process](https://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/)

**Comment by justinjc** [comment]
Resolved by [pull 15](https://github.com/uber-java/tally/pull/15). Docs will now be published to https://uber-java.github.io/tally/docs on merge to master.
