### ISSUE TITLE
Add Microbenchmarks to the code

### ISSUE THREAD

**Issue by prateek** [uber-java/tally#7]
tally-go uses Go's internal micro benchmarking tools to get an idea of allocation/performance of [common usages](https://github.com/uber-go/tally/blame/master/README.md#L186). Lets have this publish the same type of numbers for tally-java. 

Some links that might be worth investigating:
- http://www.ellipticgroup.com/html/benchmarkingArticle.html ~ common things to lookout for when doing JVM microbenchmarks
- https://github.com/google/caliper ~ little dated, dunno if it's still maintained. 
- http://java-performance.info/jmh/ ~ appears to be newer and maintained by a core OpenJDK developer

**Comment by JigarJoshi** [comment]
+1 for JMH.

**Comment by alexeykudinkin** [comment]
This has been added (somewhat) recently
