### ISSUE TITLE
What is the "tags"?

### ISSUE THREAD

**Issue by myandpr** [uber-java/tally#88]
I want know what is "tags", how to use "tags"? Is there any detailed document？
```
Map<String, String> tags = new HashMap<>(2, 1);
tags.put("dc", "east-1");
tags.put("type", "master");

Scope scope = new RootScopeBuilder()
    .reporter(reporter)
    .tags(tags)
    .reportEvery(Duration.ofSeconds(1))
```

**Comment by SokolAndrey** [comment]
You can find some documentation about data model and tags here: https://m3db.io/docs/how_to/use_as_tsdb/
tl;dr
M3 stores its data as time-series: streams of timestamp and value pairs {t1, v1}, {t2, v2},... each time series is uniquely identified by it's name and key-value string pairs called tags, which can add contextual meaning to it.
